name = "Mixers"
uuid = "2a8e4939-dab8-5edc-8f64-72a8776f13de"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[extras]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Parameters", "Unitful", "Test"]
